### PR TITLE
Fix categorical scitypes

### LINKED ISSUE #80: SMOTEN `input_scitype` and doc string
```julia
julia> input_scitype(Imbalance.MLJ.SMOTEN)
Tuple{Union{Table{<:AbstractVector{<:Finite}}, AbstractMatrix{Finite}}, AbstractVector}
```
The `AbstractMatrix{Finite}` should be `Abstract{<:Finite}`. 

And the doc-string is contrary to this:

```
 Transform Inputs
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

    •  X: A matrix or table of floats where each row is an observation from the dataset

    •  y: An abstract vector of labels (e.g., strings) that correspond to the
       observations in X
```

### PR DESCRIPTION
**Pull request by EssamWisam**
This PR involves three commits that respectively close #80, #79 and fixdocumentation to expose the fact that random oversampling and undersampling do indeed support tables with categorical data (not just floats).

### CODE REVIEW

File: src/oversampling_methods/random_walk/interface_mlj.jl [hunk 1]
```diff
@@ -30,6 +30,12 @@ Oversample data X, y using RandomWalkOversampler
 function MMI.transform(s::RandomWalkOversampler, _, X, y)
     random_walk_oversample(X, y; ratios = s.ratios, rng = s.rng, try_preserve_type=s.try_preserve_type)
 end
+function MMI.transform(s::RandomWalkOversampler, _, 
+                       X::AbstractMatrix{<:AbstractFloat}, 
+                       y::AbstractVector, 
+                       cat_inds::AbstractVector{<:Int})
```
Comment (ablaom) [inline src/oversampling_methods/random_walk/interface_mlj.jl:36]: This is a problem. You can't pass "metadata" like `cat_inds` in this way. All the arguments after `_` must be "observational" data sharing a common number of observations (needed in algorithms that subsample). And currently you can't pass as kwarg either, because kwargs are not passed on  by `(::Machine, ...)`, for example. The only way would be to introduce a hyperparameter (field of the model struct). 

Maybe you just want to drop support for matrices in the MLJ interface.

Comment (EssamWisam) [reply src/oversampling_methods/random_walk/interface_mlj.jl:36]: I was going to ask before doing this but when the tests I made for it passed I thought it should be perfectly okay. Alright will just revert back to the case where all methods have matrix support except purely heterogenous ones that apply logic differently to each kind (`SMOTENC` and `RandomWalkOversampler`).

Thank you for your comment.

**Review by ablaom — APPROVED** [review]
Good to go, thanks.
